# HuggingFace Spaces configuration
title: WEB.BUILDING.GENIOUS
emoji: 🤖
colorFrom: blue
colorTo: purple
sdk: docker
app_port: 7860
pinned: false
license: mit
short_description: AI-Powered Web Application Generator with Multi-Provider Support
tags:
  - ai
  - web-development
  - code-generation
  - nextjs
  - supabase
models:
  - openai/gpt-4
  - meta-llama/Llama-2-70b-chat-hf
datasets: []
