"use client"

import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Download, FileCode, MessageSquare, Package } from "lucide-react"
import { downloadProject, downloadCodeFiles, downloadChatHistory, type Project } from "@/lib/file-manager"

interface DownloadMenuProps {
  generatedCode: { html: string; css: string; js: string }
  messages: any[]
  projectName?: string
}

export function DownloadMenu({ generatedCode, messages, projectName = "my-project" }: DownloadMenuProps) {
  const handleDownloadProject = () => {
    const project: Project = {
      name: projectName,
      description: "Generated by WEB.BUILDING.GENIOUS",
      files: [
        { name: "index.html", content: generatedCode.html, type: "html" },
        { name: "styles.css", content: generatedCode.css, type: "css" },
        { name: "script.js", content: generatedCode.js, type: "js" },
      ].filter((file) => file.content.trim()),
      chat_messages: messages,
    }
    downloadProject(project)
  }

  const handleDownloadCode = () => {
    downloadCodeFiles(generatedCode, projectName)
  }

  const handleDownloadChat = () => {
    downloadChatHistory(messages, projectName)
  }

  const hasCode = generatedCode.html || generatedCode.css || generatedCode.js
  const hasMessages = messages.length > 0

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm">
          <Download className="w-4 h-4 mr-2" />
          Download
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handleDownloadProject} disabled={!hasCode && !hasMessages}>
          <Package className="w-4 h-4 mr-2" />
          Complete Project
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={handleDownloadCode} disabled={!hasCode}>
          <FileCode className="w-4 h-4 mr-2" />
          Code Files Only
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleDownloadChat} disabled={!hasMessages}>
          <MessageSquare className="w-4 h-4 mr-2" />
          Chat History
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
